server:
  port: 8080
spring:
  application:
    # 应用的名称 可选
    name: reggie_take_out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?characterEncoding=utf-8&useSSL=false
    username: root
    password: dawn
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      # 设置单个文件最大长度
      max-file-size: 10MB
      #最大请求文件的大小
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    port: 465
    username: 3050511039@qq.com
    password: gbdqzfmmieppdgfb
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名的字段名的下划线去掉，按照驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: E:\各科资料\瑞吉外卖\1 瑞吉外卖项目\资料\图片资源\

